[versions]
assertj = "3.27.6"
gradleOci-junitJupiter = "0.8.0"
hivemq-extensionSdk = "4.1.0"
jetbrains-annotations = "26.0.2-1"
junit-jupiter = "5.10.2"
logback = "1.5.23"
mockito = "5.21.0"
owner = "1.0.12"
prometheus-simpleClient = "0.16.0"
testcontainers = "2.0.3"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
gradleOci-junitJupiter = { module = "io.github.sgtsilvio:gradle-oci-junit-jupiter", version.ref = "gradleOci-junitJupiter" }
hivemq-extensionSdk = { module = "com.hivemq:hivemq-extension-sdk", version.ref = "hivemq-extensionSdk" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
owner = { module = "org.aeonbits.owner:owner", version.ref = "owner" }
prometheus-simpleClient = { module = "io.prometheus:simpleclient", version.ref = "prometheus-simpleClient" }
prometheus-simpleClient-dropwizard = { module = "io.prometheus:simpleclient_dropwizard", version.ref = "prometheus-simpleClient" }
prometheus-simpleClient-httpserver = { module = "io.prometheus:simpleclient_httpserver", version.ref = "prometheus-simpleClient" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-hivemq = { module = "org.testcontainers:testcontainers-hivemq", version.ref = "testcontainers" }
testcontainers-junitJupiter = { module = "org.testcontainers:testcontainers-junit-jupiter", version.ref = "testcontainers" }

[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
hivemq-extension = { id = "com.hivemq.extension", version = "4.0.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.24.0" }
